### PR TITLE
Add beforeBuild and wrapBuild filters.

### PR DESCRIPTION
**Pull request by timmfin**
Similar to [afterBuild](https://github.com/stefanpenner/broccoli-stew/blob/master/lib/afterBuild.js), but calls a callback before the input tree is read and before & after the input tree is read (respectively).

### CODE REVIEW

**Comment by stefanpenner** [comment]
Awesome. Mind dasherizing the new modules that were added?

**Comment by timmfin** [comment]
Sure thing, did the pre-existing `afterBuild.js` too while I was there.

**Comment by stefanpenner** [comment]
The readme links need to be updated now


Why log errors, this should be the cli responsibilities not stew

**Comment by timmfin** [comment]
Removed errors for missing inputTree.

**Comment by stefanpenner** [comment]
looks VGTM

**Comment by stefanpenner** [comment]
published as 0.3.0

**Pull request merged**
