### PR TITLE
Add broccoli-plugin to project dependencies

### PR DESCRIPTION
**Pull request by maxmalov**
This is used here https://github.com/stefanpenner/broccoli-stew/blob/master/lib/utils/noop.js#L3 but wasn't included into package dependencies

### CODE REVIEW

**Comment by stefanpenner** [comment]
Oops!

**Comment by toobulkeh** [comment]
can this be released?

**Comment by stefanpenner** [comment]
Ya, releasing now. (just got in the office)

**Comment by cyril-sf** [comment]
I was about to complain to you 😛

**Comment by stefanpenner** [comment]
released as v1.4.2 🎉

**Comment by stefanpenner** [comment]
@cyril-sf  complain to me at you own risk ;)

**Comment by stefanpenner** [comment]
Thanks for the PR!

**Pull request merged**
