### PR TITLE
Bumping broccoli-test-helpers

### PR DESCRIPTION
**Pull request by chadhietala**
I have exposed the in scope builder in the returned `results`. While this project does not need to test rebuilds I would like like to keep abreast with the latest.

__Example Usage__

```
  it('should invalidate the cache if an addon changes', function () {
    var module = path.join(__dirname, '..', 'node_modules', 'my-addon');
    var target = path.join(module, 'index.js');

    return prePackager(find('.'), {
      entries: ['example-app']
    }).then(function(results) {
      expect(results.files).to.deep.equal([
        'ember-moment/helpers/ago.js',
        'ember-moment/helpers/duration.js',
        'ember-moment/helpers/moment.js',
        'example-app/app.js',
        'example-app/config/environment.js',
        'example-app/initializers/ember-moment.js',
        'example-app/router.js'
      ]);
    });
    var code = fs.readFileSync(target, 'utf-8');
    code = code.replace('other.something()', 'other.something()+1');
    return results.builder.build();
// ---------------^
  }).then(function(results) {
     var changedFile = fs.readFileSync(target, 'utf-8');
     expect(changedFile.indexOf('other.something()+1') > -1).to.be.ok();
  });
});
```

### CODE REVIEW

**Comment by stefanpenner** [comment]
@chadhietala that is rad, this will make testing broccoli stuff /w rebuilds really nice!

**Comment by stefanpenner** [comment]
cc @joliss

**Comment by chadhietala** [comment]
@stefanpenner literally 1 line change. https://github.com/chadhietala/broccoli-test-helpers/commit/4bc3995f1bb2d1f29a83bfdcf117fd6e8156dab7

**Comment by joliss** [comment]
@chadhietala Oh that looks really cool! I'll definitely give it a spin next time I write plugin tests. Btw, perhaps you've already seen it, but I also wanted to point you at [fixturify](https://github.com/joliss/node-fixturify) in case it's useful for the test-helpers.

**Comment by joliss** [comment]
(Fixturify should perhaps also gain a `followSymlinks` option to be more useful, as a lot of Broccoli plugins use heavy symlinking these days.)

**Pull request merged**
