### PR TITLE
Introducing MagicString

### LINKED ISSUE #16: map should be source-map aware?

### PR DESCRIPTION
**Pull request by twokul**
this should allow us to painlessly update source maps ^_^

fixes #16

### CODE REVIEW

**Comment by chadhietala** [comment]
Awesome!

**Comment by stefanpenner** [comment]
:( can't seem to get this working with SM in RSVP, but it might be something else. Will investigate this weekend

**Comment by stefanpenner** [comment]
actually it seems to work, the issue is in the other module transpilers source maps. Awesome

**Comment by stefanpenner** [comment]
this doesn't yet merge SM (as far as i can tell)

**Pull request merged**
