### PR TITLE
WIP: npm.main helper

### PR DESCRIPTION
**Pull request by taras**
I rebased my branch and there are other tests failing for some reason. 

Continuation of #65

### CODE REVIEW

**Comment by stefanpenner** [comment]
> I rebased my branch and there are other tests failing for some reason.

ya,im working on those as we speak :)

**Comment by stefanpenner** [comment]
rebase will likely be green.

**Comment by taras** [comment]
@stefanpenner fixed, finally :) 

TravisCI - ok
Appveyor - fail

but they fail on different test, not `npm.main`

**Comment by stefanpenner** [comment]
> Appveyor - fail

added to my cal, will poke around this weekend.

**Comment by stefanpenner** [comment]
https://github.com/stefanpenner/broccoli-stew/pull/97

**Pull request closed without merging**
