### PR TITLE
Ensure Mapper produces stable outputs across builds

### PR DESCRIPTION
**Pull request by caitp**

### CODE REVIEW

**Comment by stefanpenner** [comment]
If this new plugin is a drop in with better semantics. It seems like the biggest benefit would be to get it merged with broccoli-filter. Can you share reasons why this should not be the case?

**Comment by caitp** [comment]
Jo has a few branches trying to update filter to the new stable semantics, but they've never landed upstream.

I'm working to try to ensure that it's backwards compatible and stable until the new api revamp is finished, and maybe they'll be interested in getting it upstream, maybe not. In case it's not 100% backwards compatible, it's downstream for now

**Comment by stefanpenner** [comment]
@caitp awesome, the reason I ask. Is that it would minimize much work if all broccoli-filters "just worked".

I am fine with an interim step for sure, I just want to make sure the ecosystem as a whole is spiraling the right way.

**Comment by stefanpenner** [comment]
mind rebasing?

**Comment by stefanpenner** [comment]
the tests appear to actually only test that the rebuild API is used, not that the paths are actually stable.

**Comment by caitp** [comment]
well it verifies that the outputPath doesn't change, at any rate. To have a more meaningful test, a mock plugin that depends on stable input paths would have to be devised. Our incremental wrapper plugin is a bit heavy to use for that purpose. Got a simpler one in mind?

**Comment by stefanpenner** [comment]
> well it verifies that the outputPath doesn't change, at any rate.

Yes, but the test is tightly coupled to the rebuild API artifacts (subject having `.cachePath` and `.outputPath`) but not the actual intended behavior.

I believe if broccoli-filter is swapped back in, the tests will fail not because of instability but rather because subject does not the properties in question.

> Got a simpler one in mind?

I am unfamiliar with your incremental wrapper plugin, but my thought was just to create a second cauliflower filter, append it after map in the pipeline. This filter could remember which `string` `relativePath` pairs it received as arguments to `processString`. This data would reveal stability

**Comment by caitp** [comment]
It's not quite that simple, because of the cacheing strategy used by Filter. Busting the cache with a real filesystem isn't great for unit testing.

**Comment by stefanpenner** [comment]
> Busting the cache with a real filesystem isn't great for unit testing.

yes, these are all basically integration level already. Unit, isn't truthful work if multiple collaborators (a builder) is required.

I believe that the tests here isn't really valid, or at least its description is misleading. 

I suspect the resolution is as follows:

- [ ] update description, to be something like "correctly utilizes the broccoli.rebuild api"
- [ ] merge.

**Comment by caitp** [comment]
There you go, that test fails with broccoli-filter but passes with cauliflower. Unfortunately it's a bit tightly coupled to private properties of the Filter class, so maybe that could be iterated on a bit.

**Comment by stefanpenner** [comment]
@caitp fantastic.

**Comment by caitp** [comment]
oh uh, you know, apparently I didn't remove that "revert" commit, so there's some extra stuff in package.json atm

**Comment by stefanpenner** [comment]
@caitp feel free to follow up with an additional commit if your would like

**Comment by caitp** [comment]
I would just force-push with that last commit removed, can't really send a pull request for that

**Comment by stefanpenner** [comment]
> I would just force-push with that last commit removed, can't really send a pull request for that

feel free to force push

**Pull request merged**
